int _putchar(int c);
int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers(void);
void print_line(int n);
void more_numbers(int n);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
